#!/bin/bash

setup_motd()
{
    echo >> /etc/motd
    echo 'You can configure this system or install to disk using "sudo k3os install"' >> /etc/motd
}

setup_base()
{
    # Give ISO image a few chances to mount. Default implementation sometimes fails
    # (blkid -L K3OS returns nothing) when remotly mounting ISO (i.e. when using
    # HP iLO Integrated Remote Console).
    for (( r=0; r < 10; r++)); do
        K3OS_ISO=$(blkid -L K3OS || true)
        if [ -n "$K3OS_ISO" ]; then
            success=true
            mount -o ro $(blkid -L K3OS) /.base            
            break
        fi

        pinfo "Waiting for ISO for $((r+1)) seconds"
        sleep 1
    done
    
    if [ "$success" = "true" ]; then
        pinfo "Success"
    else
        success=false
        for (( j=0; j < 5 ; j++ )); do
            for i in $(lsblk -o NAME,TYPE -n | grep -w disk | awk '{print $1}'); do
                if mount /dev/$i /.base; then
                    success=true
                    break
                fi
            done
            if [ "$success" = "true" ]; then
                break
            else
                pinfo "Waiting for USB for $((j+1)) seconds"
                sleep 1
            fi
        done
    fi
}

setup_passwd()
{
    # no passwords in live mode
    passwd -d rancher >/dev/null 2>&1
}

setup_base
setup_kernel
setup_passwd
setup_motd
